### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lafumafin** [noother/Nimda3#24]
No clue about coding. How to fix this? What am I doing wrong?

`PHP Fatal error:  Uncaught Error: Call to undefined function mb_internal_encoding() in /home/luca/Schreibtisch/nimda/Nimda3/core/defaults.php:3
Stack trace:
#0 /home/luca/Schreibtisch/nimda/Nimda3/core/Nimda.php(3): require_once()
#1 /home/luca/Schreibtisch/nimda/Nimda3/nimda(3): require_once('/home/luca/Schr...')
#2 {main}
  thrown in /home/luca/Schreibtisch/nimda/Nimda3/core/defaults.php on line 3
luca@laptop-luca:~/Schreibtisch/nimda/Nimda3$ 
`

Thy

**Comment by noother** [comment]
Hi, what version of PHP are you using and what Linux distribution?

The mbstring extension for PHP must be enabled which it is usually but apparently not for you.
Alternatively just remove the mb_internal_encoding('UTF-8'); line in core/defaults.php, it shouldn't be needed if you're on PHP 5.6 or above.

**Comment by lafumafin** [comment]
I am using Xubuntu 16.04.1 LTS (xfce 4.12.0)#
PHP  installed
php7.0-mbstring installed (just now)

New out:

`PHP Notice:  Use of undefined constant MYSQLI_BOTH - assumed 'MYSQLI_BOTH' in /home/luca/Schreibtisch/nimda/Nimda3/core/Nimda.php on line 63
PHP Notice:  Use of undefined constant MYSQLI_ASSOC - assumed 'MYSQLI_ASSOC' in /home/luca/Schreibtisch/nimda/Nimda3/core/Nimda.php on line 63
PHP Notice:  Use of undefined constant MYSQLI_NUM - assumed 'MYSQLI_NUM' in /home/luca/Schreibtisch/nimda/Nimda3/core/Nimda.php on line 63
Checking for updates..
PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /home/luca/Schreibtisch/nimda/Nimda3/classes/MySQL.php:27
Stack trace:
#0 /home/luca/Schreibtisch/nimda/Nimda3/classes/MySQL.php(36): MySQL->connect()
#1 /home/luca/Schreibtisch/nimda/Nimda3/core/Nimda.php(81): MySQL->query('SHOW TABLES LIK...')
#2 /home/luca/Schreibtisch/nimda/Nimda3/core/Nimda.php(70): Nimda->autoUpdateSQL()
#3 /home/luca/Schreibtisch/nimda/Nimda3/core/Nimda.php(33): Nimda->initBot()
#4 /home/luca/Schreibtisch/nimda/Nimda3/nimda(5): Nimda->__construct()
#5 {main}
  thrown in /home/luca/Schreibtisch/nimda/Nimda3/classes/MySQL.php on line 27
`

Is this an error because of my database?

Greetings...

**Comment by noother** [comment]
Please install php7.0-mysql and make sure extension=mysqli.so is not commented out in your /etc/php7.0/cli/php.ini (path guessed)

**Comment by lafumafin** [comment]
Thank you...Running now.
Next problem is my SQL database.

`PHP Warning:  mysqli::__construct(): (HY000/1045): Access denied for user 'luca'@'localhost' (using password: YES) in /home/luca/Schreibtisch/nimda/Nimda3/classes/MySQL.php on line 27
Access denied for user 'luca'@'localhost' (using password: YES)rm: fehlender Operand
„rm --help“ liefert weitere Informationen.
`

I tried to let him login with root rights.
`mysql_host	= localhost
mysql_user	= luca
mysql_pass	= *******
mysql_db	= nimda
`

But he didn't get access.

**Comment by noother** [comment]
Have you created the database before? Don't let him run under root.

mysql -u luca -p
# <enter password>
create database nimda;
grant all privileges on nimda.* to nimda@localhost identified by 'nimda_sql_password_here';
# change nimda.conf with the correct data

**Comment by lafumafin** [comment]
Yep, I re created it, working perfect now. Thanks a lot!

**Comment by lafumafin** [comment]
Where to change the default server and channel + name?

**Comment by noother** [comment]
In the SQL tables "servers" and "server_channels" that just got created in your database - use phpmyadmin for convenience.

**Comment by lafumafin** [comment]
alright thanks a lot

**Comment by lafumafin** [comment]
is there a function or something for showing all nimda commands?

**Comment by noother** [comment]
!help
